defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:8
version: 2
jobs:
  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set npmrc credentials
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Run lint
          command: npm run eslint
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Publish to NPM
          command: npx published

workflows:
  version: 2
  ci-cd:
    jobs:
      - publish:
          context: org-global
